language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
before_script:
  - npm install -g npm@latest
  - npm install -g expo-cli
script:
  - npm ci


jobs:
  include:
    - stage: deploy
      if: branch = dev
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
    - stage : build
      if: branch = master
      script:
        - expo build:android -t app-bundle
      

