allowBuilds:
  postinstall-postinstall: true
  react-native-elements: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.27'
  - '@expo/router-server@57.0.11'
  - babel-preset-expo@57.0.13
  - expo-modules-core@57.0.19
  - expo-modules-jsi@57.1.1
  - expo@57.0.25
  - expo-image-picker@57.0.20
  - expo-linking@57.0.11
  - expo-location@57.0.20
